[package]
name = "sorting"
version = "0.1.0"
authors = ["MichaelObvious <michael.obviouss@gmail.com>"]
edition = "2018"

[dependencies]
console_gfx = { git = "https://github.com/MichaelObvious/console_gfx.git", version = "0.0.3" }
rand = "0.7.3"
